### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by camjac251** [HugoJF/twitch-clip-downloader#8]
I'm not sure what went wrong here. I was able to scrape the clips just fine in the first half but downloading part gave an error.

```bash
✔ Found 56940 clips to download, download now? … yes
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/56940(node:41941) UnhandledPromiseRejectionWa'
    at Object.openSync (fs.js:461:3)
    at Object.writeFileSync (fs.js:1387:35)
    at /home/user/clips/twitch-clip-downloader/clip-downloader.js:30:12
    at new Promise (<anonymous>)
    at downloadClip (/home/user/clips/twitch-clip-downloader/clip-downloader.js:10:12)
    at process (/home/user/clips/twitch-clip-downloader/clip-downloader.js:38:15)
    at /home/user/clips/twitch-clip-downloader/node_modules/tiny-async-pool/lib/es7.js:18:44
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async asyncPool (/home/user/clips/twitch-clip-downloader/node_modules/tiny-async-pool/)
    at async startDownload (/home/user/clips/twitch-clip-downloader/clip-downloader.js:46:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:41941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either)
(node:41941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, p.




Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/user/clips/twitch-clip-downloader/node_modules/reques)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:768:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/user/clips/twitch-clip-downloader/node_modules/reques)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:768:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/user/clips/twitch-clip-downloader/node_modules/reques)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:768:9)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at TLSSocket.Socket._onTimeout (net.js:480:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false
}
```

**Comment by HugoJF** [comment]
Please make sure a `clips` directory exists. For whatever reason I still have not implemented the creation of this directory yet.

**Comment by camjac251** [comment]
Yup that was it. It was a bit confusing at first. Could there maybe be an error handling system in case the folder is missing? Like `error: folder missing`

**Comment by HugoJF** [comment]
Since I never really planned on releasing this tool, I never took care of this.

In future releases, instead of showing an error, the tool will just create the directory if it already doesn't exists.

If you encounter any new errors, feel free to open a new issue!

**Comment by camjac251** [comment]
I'm glad you did release it since I haven't been able to find any other clip downloader that uses the `started_at` and `ended_at` methods.
